collection:
- packageId: 1001
  packageName: 'Кусковой сахар, 3 шт.'
  count: 3
  itemName: 'Кусковой сахар'
  tid: 41007
- packageId: 1002
  packageName: 'Морковь, 3 шт.'
  count: 3
  itemName: 'Морковь'
  tid: 41006
- packageId: 1003
  packageName: 'Кукуруза, 3 шт.'
  count: 3
  itemName: 'Кукуруза'
  tid: 41001
- packageId: 1004
  packageName: 'Ячмень, 3 шт.'
  count: 3
  itemName: 'Ячмень'
  tid: 41003
- packageId: 1005
  packageName: 'Луговая трава, 2 шт.'
  count: 2
  itemName: 'Луговая трава'
  tid: 41005
- packageId: 1008
  packageName: 'Луговая трава, 2 шт.'
  count: 2
  itemName: 'Луговая трава'
  tid: 41005
- packageId: 1007
  packageName: 'Бобы, 2 шт.'
  count: 2
  itemName: 'Бобы'
  tid: 41002
- packageId: 1011
  packageName: 'Кристалл-материал, 1 шт.'
  count: 1
  itemName: 'Кристалл-материал'
  tid: 45001
- packageId: 1012
  packageName: 'Эликсир роста, 1 шт.'
  count: 1
  itemName: 'Эликсир роста'
  tid: 43001
- packageId: 1013
  packageName: 'Расслабляющая мазь, 1 шт.'
  count: 1
  itemName: 'Расслабляющая мазь'
  tid: 44001
- packageId: 1014
  packageName: 'Антибактериальный крем, 1 шт.'
  count: 1
  itemName: 'Антибактериальный крем'
  tid: 44003
- packageId: 1015
  packageName: 'Временная шина, 1 шт.'
  count: 1
  itemName: 'Временная шина'
  tid: 44005
- packageId: 1016
  packageName: 'Удочка с морковкой, 10 шт.'
  count: 10
  itemName: 'Удочка с морковкой'
  tid: 42001
- packageId: 1017
  packageName: 'Лук, 10 шт.'
  count: 10
  itemName: 'Лук'
  tid: 42002
- packageId: 1018
  packageName: 'Сонпхён с бобами, 1 шт.'
  count: 1
  itemName: 'Сонпхён с бобами'
  tid: 46013
- packageId: 1019
  packageName: 'Сонпхён с мёдом, 1 шт.'
  count: 1
  itemName: 'Сонпхён с мёдом'
  tid: 46014
- packageId: 1020
  packageName: 'Кусковой сахар, 5 шт.'
  count: 5
  itemName: 'Кусковой сахар'
  tid: 41007
- packageId: 1021
  packageName: 'Морковь, 5 шт.'
  count: 5
  itemName: 'Морковь'
  tid: 41006
- packageId: 1022
  packageName: 'Кукуруза, 5 шт.'
  count: 5
  itemName: 'Кукуруза'
  tid: 41001
- packageId: 1023
  packageName: 'Ячмень, 5 шт.'
  count: 5
  itemName: 'Ячмень'
  tid: 41003
- packageId: 1024
  packageName: 'Луговая трава, 5 шт.'
  count: 5
  itemName: 'Луговая трава'
  tid: 41005
- packageId: 1025
  packageName: 'Бобы, 5 шт.'
  count: 5
  itemName: 'Бобы'
  tid: 41002
- packageId: 1026
  packageName: 'Луговая трава, 5 шт.'
  count: 5
  itemName: 'Луговая трава'
  tid: 41005
- packageId: 1030
  packageName: 'Удочка с морковкой, 5 шт.'
  count: 5
  itemName: 'Удочка с морковкой'
  tid: 42001
- packageId: 1031
  packageName: 'Лук, 5 шт.'
  count: 5
  itemName: 'Лук'
  tid: 42002
- packageId: 1032
  packageName: 'Хэллоуинская шляпа ведьмы, 7 шт.'
  count: 7
  itemName: 'Хэллоуинская шляпа ведьмы'
  tid: 10159
- packageId: 1033
  packageName: 'Мини-шляпа с тыквой Джека, 7 шт.'
  count: 7
  itemName: 'Мини-шляпа с тыквой Джека'
  tid: 10160
- packageId: 1034
  packageName: 'Хэллоуинский колпак тёмного чародея, 7 шт.'
  count: 7
  itemName: 'Хэллоуинский колпак тёмного чародея'
  tid: 30154
- packageId: 1035
  packageName: 'Клетчатая шляпа с тыквой Джека, 7 шт.'
  count: 7
  itemName: 'Клетчатая шляпа с тыквой Джека'
  tid: 30155
- packageId: 1036
  packageName: 'Хэллоуинская конфета, 1 шт.'
  count: 1
  itemName: 'Хэллоуинская конфета'
  tid: 46016
- packageId: 1037
  packageName: 'Хэллоуинский шоколад, 1 шт.'
  count: 1
  itemName: 'Хэллоуинский шоколад'
  tid: 46017
- packageId: 1038
  packageName: 'Колокольчик смотрителя, 1 шт.'
  count: 1
  itemName: 'Колокольчик смотрителя'
  tid: 45005
- packageId: 1039
  packageName: 'Эликсир мастерства, 1 шт.'
  count: 1
  itemName: 'Эликсир мастерства'
  tid: 46020
- packageId: 1040
  packageName: 'Значок идеального старта, 1 шт.'
  count: 1
  itemName: 'Значок идеального старта'
  tid: 46021
- packageId: 1042
  packageName: 'Яйцо удачи: Дорф (ур. 1), 1 шт.'
  count: 1
  itemName: 'Яйцо удачи: Дорф (ур. 1)'
  tid: 90006
- packageId: 1043
  packageName: 'Яйцо удачи: Дорф (ур. 2), 2 шт.'
  count: 2
  itemName: 'Яйцо удачи: Дорф (ур. 2)'
  tid: 90007
- packageId: 1044
  packageName: 'Яйцо удачи: Дорф (ур. 3), 3 шт.'
  count: 3
  itemName: 'Яйцо удачи: Дорф (ур. 3)'
  tid: 90008
- packageId: 1045
  packageName: 'Яйцо удачи: Дрэн (ур. 1), 1 шт.'
  count: 1
  itemName: 'Яйцо удачи: Дрэн (ур. 1)'
  tid: 90004
- packageId: 1046
  packageName: 'Яйцо удачи: Дрэн (ур. 2), 2 шт.'
  count: 2
  itemName: 'Яйцо удачи: Дрэн (ур. 2)'
  tid: 90005
- packageId: 1047
  packageName: 'Яйцо удачи: Дрэн (ур. 3), 3 шт.'
  count: 3
  itemName: 'Яйцо удачи: Дрэн (ур. 3)'
  tid: 90011
- packageId: 1048
  packageName: 'Яйцо удачи: Табиа (ур. 1), 1 шт.'
  count: 1
  itemName: 'Яйцо удачи: Табиа (ур. 1)'
  tid: 90013
- packageId: 1049
  packageName: 'Яйцо удачи: Табиа (ур. 2), 2 шт.'
  count: 2
  itemName: 'Яйцо удачи: Табиа (ур. 2)'
  tid: 90014
- packageId: 1050
  packageName: 'Яйцо удачи: Табиа (ур. 3), 3 шт.'
  count: 3
  itemName: 'Яйцо удачи: Табиа (ур. 3)'
  tid: 90015
- packageId: 1051
  packageName: 'Яйцо удачи: Форе (ур. 1), 1 шт.'
  count: 1
  itemName: 'Яйцо удачи: Форе (ур. 1)'
  tid: 90010
- packageId: 1052
  packageName: 'Яйцо удачи: Форе (ур. 2), 2 шт.'
  count: 2
  itemName: 'Яйцо удачи: Форе (ур. 2)'
  tid: 90001
- packageId: 1053
  packageName: 'Яйцо удачи: Форе (ур. 3), 3 шт.'
  count: 3
  itemName: 'Яйцо удачи: Форе (ур. 3)'
  tid: 90002
- packageId: 1054
  packageName: 'Смена имени питомца, 1 шт.'
  count: 1
  itemName: 'Смена имени питомца'
  tid: 45002
- packageId: 1055
  packageName: 'Броня Рождество, 3 шт.'
  count: 3
  itemName: 'Броня Рождество'
  tid: 20123
- packageId: 1056
  packageName: 'Украшение Рождество, 3 шт.'
  count: 3
  itemName: 'Украшение Рождество'
  tid: 20124
- packageId: 1057
  packageName: 'Подковы Рождество, 3 шт.'
  count: 3
  itemName: 'Подковы Рождество'
  tid: 20125
- packageId: 1058
  packageName: 'Снаряжение Рождество, 3 шт.'
  count: 3
  itemName: 'Снаряжение Рождество'
  tid: 20126
- packageId: 1059
  packageName: 'Ободок с рогами Рудольфа, 3 шт.'
  count: 3
  itemName: 'Ободок с рогами Рудольфа'
  tid: 30160
- packageId: 1060
  packageName: 'Ободок с носом Рудольфа, 3 шт.'
  count: 3
  itemName: 'Ободок с носом Рудольфа'
  tid: 10165
- packageId: 1061
  packageName: 'Эликсир гривы, 1 шт.'
  count: 1
  itemName: 'Эликсир гривы'
  tid: 46004
- packageId: 1062
  packageName: 'Телепорт, 1 шт.'
  count: 1
  itemName: 'Телепорт'
  tid: 70002
- packageId: 1063
  packageName: 'Очищенный кристалл, 1 шт.'
  count: 1
  itemName: 'Очищенный кристалл'
  tid: 46018
- packageId: 1064
  packageName: 'Эликсир наездника, 1 шт.'
  count: 1
  itemName: 'Эликсир наездника'
  tid: 46003
- packageId: 1065
  packageName: 'Колокольчик смотрителя, 1 шт.'
  count: 1
  itemName: 'Колокольчик смотрителя'
  tid: 45005
- packageId: 1066
  packageName: 'Эликсир мастерства, 1 шт.'
  count: 1
  itemName: 'Эликсир мастерства'
  tid: 46020
- packageId: 1067
  packageName: 'Эликсир роста, 1 шт.'
  count: 1
  itemName: 'Эликсир роста'
  tid: 43001
- packageId: 1068
  packageName: 'Удочка с морковкой, 2 шт.'
  count: 2
  itemName: 'Удочка с морковкой'
  tid: 42001
- packageId: 1069
  packageName: 'Лук, 2 шт.'
  count: 2
  itemName: 'Лук'
  tid: 42002
- packageId: 1070
  packageName: 'Кусковой сахар, 3 шт.'
  count: 3
  itemName: 'Кусковой сахар'
  tid: 41007
- packageId: 1071
  packageName: 'Морковь, 3 шт.'
  count: 3
  itemName: 'Морковь'
  tid: 41006
- packageId: 1072
  packageName: 'Кукуруза, 3 шт.'
  count: 3
  itemName: 'Кукуруза'
  tid: 41001
- packageId: 1073
  packageName: 'Ячмень, 3 шт.'
  count: 3
  itemName: 'Ячмень'
  tid: 41003
- packageId: 1074
  packageName: 'Луговая трава, 2 шт.'
  count: 2
  itemName: 'Луговая трава'
  tid: 41005
- packageId: 1075
  packageName: 'Бобы, 2 шт.'
  count: 2
  itemName: 'Бобы'
  tid: 41002
- packageId: 1076
  packageName: 'Луговая трава, 2 шт.'
  count: 2
  itemName: 'Луговая трава'
  tid: 41005
- packageId: 1077
  packageName: 'Кристалл-материал, 1 шт.'
  count: 1
  itemName: 'Кристалл-материал'
  tid: 45001
- packageId: 1081
  packageName: 'Расслабляющая мазь, 1 шт.'
  count: 1
  itemName: 'Расслабляющая мазь'
  tid: 44001
- packageId: 1082
  packageName: 'Антибактериальный крем, 1 шт.'
  count: 1
  itemName: 'Антибактериальный крем'
  tid: 44003
- packageId: 1083
  packageName: 'Временная шина, 1 шт.'
  count: 1
  itemName: 'Временная шина'
  tid: 44005
